In [2]:
import pandas as pd
import numpy as np

## Project 1 — Meridian Insurance Co. (Titanic passenger data)

In [17]:
titanic_dataset = pd.read_csv('Dataset/Titanic-Dataset.csv',index_col='PassengerId')

### 1. Load the dataset and display the first 8 rows and the last 5 rows.

In [18]:
titanic_dataset.head(8)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [19]:
titanic_dataset.tail(5)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

### 2.Print the shape, column names, and dtype of every column.

In [23]:
# shape
shape = titanic_dataset.shape
print(f'Total column : {shape[0]} \n Total row : {shape[1]}')

Total column : 891
 Total row : 11

In [29]:
# Column names
column_names = titanic_dataset.columns.tolist()
print(f'The name of all column are : {column_names}')

The name of all column are : ['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [36]:
#dtype
dtype = titanic_dataset.dtypes
print(f'The datatype of each column is : \n{dtype}')

The datatype of each column is :
Survived      int64
Pclass        int64
Name            str
Sex             str
Age         float64
SibSp         int64
Parch         int64
Ticket          str
Fare        float64
Cabin           str
Embarked        str
dtype: object

### 3.Use .info() and .describe() to summarize the dataset; note in a comment which columns have missing values and how many.

In [38]:
titanic_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    str
 3   Sex       891 non-null    str
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    str
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    str
 10  Embarked  889 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 76.7 KB

In [39]:
titanic_dataset.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

### 4. Select only Name, Sex, Age, and Survived into a new DataFrame.

###

In [47]:
new_titanic_df = titanic_dataset[['Name','Sex','Age','Survived']]
new_titanic_df.set_index('Name',inplace=True)

In [48]:
new_titanic_df

                                                       Sex   Age  Survived
Name
Braund, Mr. Owen Harris                               male  22.0         0
Cumings, Mrs. John Bradley (Florence Briggs Tha...  female  38.0         1
Heikkinen, Miss. Laina                              female  26.0         1
Futrelle, Mrs. Jacques Heath (Lily May Peel)        female  35.0         1
Allen, Mr. William Henry                              male  35.0         0
...                                                    ...   ...       ...
Montvila, Rev. Juozas                                 male  27.0         0
Graham, Miss. Margaret Edith                        female  19.0         1
Johnston, Miss. Catherine Helen "Carrie"            female   NaN         0
Behr, Mr. Karl Howell                                 male  26.0         1
Dooley, Mr. Patrick                                   male  32.0         0

[891 rows x 3 columns]

###

### 5. Using .loc, get all passengers older than 60. Using .iloc, get rows 100 through 110.

In [52]:
titanic_dataset.loc[titanic_dataset['Age']>60].head(5)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S

In [55]:
titanic_dataset.iloc[99:110]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
100,0,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0000,NaN,S
101,0,3,"Petranec, Miss. Matilda",female,28.0,0,0,349245,7.8958,NaN,S
102,0,3,"Petroff, Mr. Pastcho (""Pentcho"")",male,NaN,0,0,349215,7.8958,NaN,S
103,0,1,"White, Mr. Richard Frasar",male,21.0,0,1,35281,77.2875,D26,S
104,0,3,"Johansson, Mr. Gustaf Joel",male,33.0,0,0,7540,8.6542,NaN,S
105,0,3,"Gustafsson, Mr. Anders Vilhelm",male,37.0,2,0,3101276,7.9250,NaN,S
106,0,3,"Mionoff, Mr. Stoytcho",male,28.0,0,0,349207,7.8958,NaN,S
107,1,3,"Salkjelsvik, Miss. Anna Kristine",female,21.0,0,0,343120,7.6500,NaN,S
108,1,3,"Moss, Mr. Albert Johan",male,NaN,0,0,312991,7.7750,NaN,S
109,0,3,"Rekic, Mr. Tido",male,38.0,0,0,349249,7.8958,NaN,S
110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q

### 6. Filter to show only female, 1st-class passengers who survived.

In [68]:
female_only = titanic_dataset.groupby('Sex').get_group('female')

In [77]:
female_only.dtypes

Survived      int64
Pclass        int64
Name            str
Sex             str
Age         float64
SibSp         int64
Parch         int64
Ticket          str
Fare        float64
Cabin           str
Embarked        str
dtype: object

In [79]:
final_answer = female_only[(female_only['Pclass'] == 1) & (female_only['Survived'] == 1)]

In [ ]:
finally_a

             Survived  Pclass  \
PassengerId
2                   1       1
4                   1       1
12                  1       1
32                  1       1
53                  1       1
...               ...     ...
857                 1       1
863                 1       1
872                 1       1
880                 1       1
888                 1       1

                                                          Name     Sex   Age  \
PassengerId
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
12                                    Bonnell, Miss. Elizabeth  female  58.0
32              Spencer, Mrs. William Augustus (Marie Eugenie)  female   NaN
53                    Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.0
...                                                        ...     ...   ...
857                 Wick, Mrs. George Dennick (Mary Hitchcock)  female  45.0
863          Swift, Mrs. Frederick Joel (Margaret Welles Ba...  female  48.0
872           Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0
880              Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0
888                               Graham, Miss. Margaret Edith  female  19.0

             SibSp  Parch    Ticket      Fare Cabin Embarked
PassengerId
2                1      0  PC 17599   71.2833   C85        C
4                1      0    113803   53.1000  C123        S
12               0      0    113783   26.5500  C103        S
32               1      0  PC 17569  146.5208   B78        C
53               1      0  PC 17572   76.7292   D33        C
...            ...    ...       ...       ...   ...      ...
857              1      1     36928  164.8667   NaN        S
863              0      0     17466   25.9292   D17        S
872              1      1     11751   52.5542   D35        S
880              0      1     11767   83.1583   C50        C
888              0      0    112053   30.0000   B42        S

[91 rows x 11 columns]