In [192]:
import pandas as pd
import numpy as np

## Project 1 — Meridian Insurance Co. (Titanic passenger data)

In [193]:
titanic_dataset = pd.read_csv('Dataset/Titanic-Dataset.csv',index_col='PassengerId')

### 1. Load the dataset and display the first 8 rows and the last 5 rows.

In [194]:
titanic_dataset.head(8)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [195]:
titanic_dataset.tail(5)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

### 2.Print the shape, column names, and dtype of every column.

In [196]:
# shape
shape = titanic_dataset.shape
print(f'Total column : {shape[0]} \n Total row : {shape[1]}')

Total column : 891
 Total row : 11

In [197]:
# Column names
column_names = titanic_dataset.columns.tolist()
print(f'The name of all column are : {column_names}')

The name of all column are : ['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [198]:
#dtype
dtype = titanic_dataset.dtypes
print(f'The datatype of each column is : \n{dtype}')

The datatype of each column is :
Survived      int64
Pclass        int64
Name            str
Sex             str
Age         float64
SibSp         int64
Parch         int64
Ticket          str
Fare        float64
Cabin           str
Embarked        str
dtype: object

### 3.Use .info() and .describe() to summarize the dataset; note in a comment which columns have missing values and how many.

In [199]:
titanic_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    str
 3   Sex       891 non-null    str
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    str
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    str
 10  Embarked  889 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 76.7 KB

In [200]:
titanic_dataset.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

### 4. Select only Name, Sex, Age, and Survived into a new DataFrame.

###

In [201]:
new_titanic_df = titanic_dataset[['Name','Sex','Age','Survived']]
new_titanic_df.set_index('Name',inplace=True)

In [202]:
new_titanic_df

                                                       Sex   Age  Survived
Name
Braund, Mr. Owen Harris                               male  22.0         0
Cumings, Mrs. John Bradley (Florence Briggs Tha...  female  38.0         1
Heikkinen, Miss. Laina                              female  26.0         1
Futrelle, Mrs. Jacques Heath (Lily May Peel)        female  35.0         1
Allen, Mr. William Henry                              male  35.0         0
...                                                    ...   ...       ...
Montvila, Rev. Juozas                                 male  27.0         0
Graham, Miss. Margaret Edith                        female  19.0         1
Johnston, Miss. Catherine Helen "Carrie"            female   NaN         0
Behr, Mr. Karl Howell                                 male  26.0         1
Dooley, Mr. Patrick                                   male  32.0         0

[891 rows x 3 columns]

###

### 5. Using .loc, get all passengers older than 60. Using .iloc, get rows 100 through 110.

In [203]:
titanic_dataset.loc[titanic_dataset['Age']>60].head(5)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S

In [204]:
titanic_dataset.iloc[99:110]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
100,0,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0000,NaN,S
101,0,3,"Petranec, Miss. Matilda",female,28.0,0,0,349245,7.8958,NaN,S
102,0,3,"Petroff, Mr. Pastcho (""Pentcho"")",male,NaN,0,0,349215,7.8958,NaN,S
103,0,1,"White, Mr. Richard Frasar",male,21.0,0,1,35281,77.2875,D26,S
104,0,3,"Johansson, Mr. Gustaf Joel",male,33.0,0,0,7540,8.6542,NaN,S
105,0,3,"Gustafsson, Mr. Anders Vilhelm",male,37.0,2,0,3101276,7.9250,NaN,S
106,0,3,"Mionoff, Mr. Stoytcho",male,28.0,0,0,349207,7.8958,NaN,S
107,1,3,"Salkjelsvik, Miss. Anna Kristine",female,21.0,0,0,343120,7.6500,NaN,S
108,1,3,"Moss, Mr. Albert Johan",male,NaN,0,0,312991,7.7750,NaN,S
109,0,3,"Rekic, Mr. Tido",male,38.0,0,0,349249,7.8958,NaN,S
110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q

### 6. Filter to show only female, 1st-class passengers who survived.

In [205]:
female_only = titanic_dataset.groupby('Sex').get_group('female')

In [206]:
female_only.dtypes

Survived      int64
Pclass        int64
Name            str
Sex             str
Age         float64
SibSp         int64
Parch         int64
Ticket          str
Fare        float64
Cabin           str
Embarked        str
dtype: object

In [207]:
final_answer = female_only[(female_only['Pclass'] == 1) & (female_only['Survived'] == 1)]

In [208]:
final_answer.sample(5)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
195,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.0,0,0,PC 17610,27.7208,B4,C
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C
89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
311,1,1,"Hays, Miss. Margaret Bechstein",female,24.0,0,0,11767,83.1583,C54,C

### 7. Count how many passengers embarked from each port (Embarked) with value_counts(), including missing values in the count.

In [209]:
titanic_dataset['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [210]:
titanic_dataset['Embarked'].isnull().sum()

np.int64(2)

### 8. Fill missing Age with the median age, fill missing Embarked with the most frequent port, and drop the Cabin column entirely (it's mostly missing).

In [211]:
titanic_dataset.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [212]:
titanic_dataset = titanic_dataset.drop(columns=['Cabin'])

In [213]:
titanic_dataset['Age'] = titanic_dataset['Age'].fillna(titanic_dataset['Age'].mean())
titanic_dataset['Embarked'] = titanic_dataset['Embarked'].fillna(titanic_dataset['Embarked'].mode()[0])

In [214]:
titanic_dataset.isnull().sum()

Survived    0
Pclass      0
Name        0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    0
dtype: int64

In [215]:
titanic_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    str
 3   Sex       891 non-null    str
 4   Age       891 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    str
 8   Fare      891 non-null    float64
 9   Embarked  891 non-null    str
dtypes: float64(2), int64(4), str(4)
memory usage: 69.7 KB

### 9. Create an AgeGroup column that bins Age into Child (0–12), Teen (13–19), Adult (20–59), Senior (60+) using pd.cut().

In [216]:
bins = [-1,12,19,59,float('inf')]

labels = ['Child','Teen','Adult','Senior']

titanic_dataset['AgeGroup'] = pd.cut(titanic_dataset['Age'],bins=bins,labels=labels)

In [217]:
titanic_dataset.sample(5)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,AgeGroup
PassengerId,,,,,,,,,,,
449,1,3,"Baclini, Miss. Marie Catherine",female,5.000000,2,1,2666,19.2583,C,Child
392,1,3,"Jansson, Mr. Carl Olof",male,21.000000,0,0,350034,7.7958,S,Adult
574,1,3,"Kelly, Miss. Mary",female,29.699118,0,0,14312,7.7500,Q,Adult
727,1,2,"Renouf, Mrs. Peter Henry (Lillian Jefferys)",female,30.000000,3,0,31027,21.0000,S,Adult
830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.000000,0,0,113572,80.0000,S,Senior

### 10. Sort by Fare descending and show the top 10 highest-paying passengers.

In [218]:
titanic_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    str
 3   Sex       891 non-null    str
 4   Age       891 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    str
 8   Fare      891 non-null    float64
 9   Embarked  891 non-null    str
 10  AgeGroup  891 non-null    category
dtypes: category(1), float64(2), int64(4), str(4)
memory usage: 70.8 KB

In [219]:
titanic_dataset.sort_values('Fare',ascending=False,inplace=True)

### 11. Group by Pclass and Sex together and calculate the mean survival rate for each combination.

In [220]:
test = titanic_dataset.groupby(['Pclass','Sex'])
test['Survived'].mean()

Pclass  Sex
1       female    0.968085
        male      0.368852
2       female    0.921053
        male      0.157407
3       female    0.500000
        male      0.135447
Name: Survived, dtype: float64

In [221]:
test.groups

{(1,
  'female'): Index([259,  89, 342, 743, 312, 300, 701, 717, 381, 780, 731, 690, 319, 857,
        269, 610, 709, 298, 499, 196,  32, 326, 270, 320, 338, 335, 764, 436,
        394, 216, 582, 307, 308, 538, 821, 521, 292, 487, 413, 850, 760, 258,
        505, 231, 836, 880, 311, 376, 830,  62, 586, 559, 257, 291, 592, 497,
        276, 628, 766,  53, 219, 367,   2, 541, 642, 370, 152, 514, 330, 524,
        782, 310, 578, 357, 167, 810,   4, 872, 670, 384, 458, 572, 711, 540,
        557, 854, 843, 888, 178, 195,  12, 137, 863, 797],
       dtype='int64', name='PassengerId'),
 (1,
  'male'): Index([680, 738, 439,  28, 119, 558, 528, 378, 333, 306,
        ...
        546, 285, 169, 663, 873, 634, 264, 807, 816, 823],
       dtype='int64', name='PassengerId', length=122),
 (2,
  'female'): Index([755, 616,  44, 609, 671, 619, 721, 597, 417,  10, 581, 324, 473,  59,
        601, 802, 441, 238, 536, 531,  54, 428, 507, 881, 260, 547, 855, 427,
        433, 317, 519, 134, 313, 875, 652, 775,  99, 751,  42, 212, 727, 273,
        447, 438,  16, 162, 248, 867, 474, 707, 748, 347, 346, 358, 577, 124,
        418, 328, 444, 388, 866, 636, 200, 191, 400, 304, 323, 390,  67, 773,
         57, 527, 517,  85, 459, 718],
       dtype='int64', name='PassengerId'),
 (2,
  'male'): Index([666, 386, 121, 656,  73, 686, 184, 685, 828, 818,
        ...
        266, 220, 571, 235, 414, 675, 733, 278, 467, 482],
       dtype='int64', name='PassengerId', length=108),
 (3,
  'female'): Index([181, 793, 864,  72, 679, 639, 148, 437, 737, 234,
        ...
        503, 650, 236, 787, 377, 368, 781, 876,  20, 655],
       dtype='int64', name='PassengerId', length=144),
 (3,
  'male'): Index([202, 847, 325, 160, 693, 510, 170, 644, 839,  75,
        ...
        372, 203, 819, 844, 327, 379, 598, 180, 272, 303],
       dtype='int64', name='PassengerId', length=347)}

In [222]:
for name, group in test:
    print(f"Group: {name}")
    print(group.head(2)) # Prints the first 2 rows of each group
    print("-" * 30)

Group: (1, 'female')
             Survived  Pclass                        Name     Sex   Age  \
PassengerId
259                 1       1            Ward, Miss. Anna  female  35.0
89                  1       1  Fortune, Miss. Mabel Helen  female  23.0

             SibSp  Parch    Ticket      Fare Embarked AgeGroup
PassengerId
259              0      0  PC 17755  512.3292        C    Adult
89               3      2     19950  263.0000        S    Adult
------------------------------
Group: (1, 'male')
             Survived  Pclass                                Name   Sex   Age  \
PassengerId
680                 1       1  Cardeza, Mr. Thomas Drake Martinez  male  36.0
738                 1       1              Lesurer, Mr. Gustave J  male  35.0

             SibSp  Parch    Ticket      Fare Embarked AgeGroup
PassengerId
680              0      1  PC 17755  512.3292        C    Adult
738              0      0  PC 17755  512.3292        C    Adult
------------------------------
Group: (2, 'female')
             Survived  Pclass                              Name     Sex   Age  \
PassengerId
755                 1       2  Herman, Mrs. Samuel (Jane Laver)  female  48.0
616                 1       2               Herman, Miss. Alice  female  24.0

             SibSp  Parch  Ticket  Fare Embarked AgeGroup
PassengerId
755              1      2  220845  65.0        S    Adult
616              1      2  220845  65.0        S    Adult
------------------------------
Group: (2, 'male')
             Survived  Pclass                       Name   Sex   Age  SibSp  \
PassengerId
666                 0       2         Hickman, Mr. Lewis  male  32.0      2
386                 0       2  Davies, Mr. Charles Henry  male  18.0      0

             Parch        Ticket  Fare Embarked AgeGroup
PassengerId
666              0  S.O.C. 14879  73.5        S    Adult
386              0  S.O.C. 14879  73.5        S     Teen
------------------------------
Group: (3, 'female')
             Survived  Pclass                          Name     Sex  \
PassengerId
181                 0       3  Sage, Miss. Constance Gladys  female
793                 0       3       Sage, Miss. Stella Anna  female

                   Age  SibSp  Parch    Ticket   Fare Embarked AgeGroup
PassengerId
181          29.699118      8      2  CA. 2343  69.55        S    Adult
793          29.699118      8      2  CA. 2343  69.55        S    Adult
------------------------------
Group: (3, 'male')
             Survived  Pclass                      Name   Sex        Age  \
PassengerId
202                 0       3       Sage, Mr. Frederick  male  29.699118
847                 0       3  Sage, Mr. Douglas Bullen  male  29.699118

             SibSp  Parch    Ticket   Fare Embarked AgeGroup
PassengerId
202              8      2  CA. 2343  69.55        S    Adult
847              8      2  CA. 2343  69.55        S    Adult
------------------------------

### 12. Export the cleaned dataset to cleaned_titanic.csv without the index column.

In [223]:
titanic_dataset.info()

<class 'pandas.DataFrame'>
Index: 891 entries, 680 to 823
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    str
 3   Sex       891 non-null    str
 4   Age       891 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    str
 8   Fare      891 non-null    float64
 9   Embarked  891 non-null    str
 10  AgeGroup  891 non-null    category
dtypes: category(1), float64(2), int64(4), str(4)
memory usage: 77.6 KB

In [224]:
final_df = titanic_dataset.copy()

In [231]:
final_df.to_csv(path_or_buf='/media/leo/Disk_D/My Future/Project/Python_Libraries/Pandas/Dataset/clean_titanic_dataset.csv')